POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
"title": "triple Amazing blog post",
"author": "triple Amazing author",
"url": "https://amazingblog.com/blog/triple-amazing-post",
"likes": 126
}